baseurl: /
url: http://localhost:4000
permalink: /:year/:month/:title.html
markdown: redcarpet
lsi: true
redcarpet:
  extensions: [ smart, fenced_code_blocks ]
highlighter: rouge

source: .
destination: ./_site
plugins_dir: ./_plugins
exclude: [ 'Readme.md', 'Gemfile.lock', 'Gemfile', 'Capfile', 'config' ]
